# Build settings

title: MAEE LAB
description: "Here you can find my research, publications, and teaching portfolio."
baseurl: "" 
url: "https://YourGitHubUsername.github.io" 

# Author Information
author: Yimen Araya Ajoy
avatar: "/assets/images/Pic.jpg"
email: yimencr@gmail.com
twitter_username: ArayaYimen
github_username:  YimenAraya-Ajoy

collections:
  pages:
    output: true
    permalink: /:path/

    
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
    
# Enable Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown Processing
markdown: kramdown
highlighter: rouge
mathjax: true
